companieshouse/sic-code-api

.gitignore, DATALOAD-README.md, README.md
Add the initial README as part of the design of the sic-code-api
Ref: bi-10680
=>  add readme for design

README.md, spec/api-spec.json, spec/swagger.json
Update readme to link to swagger file
See JIRA: https://companieshouse.atlassian.net/browse/BI-10680
=> Add swagger spec json file

src/test/resources/combined_sic_activities_additional_test_data.json
Add extra data to test dataset so that Cucumber testing can use sorted datasets for more than one record returned
BI-10828
=> Add extra test data for Cucumber test so we can test ordered results

src/main/java/uk/gov/companieshouse/siccode/api/search/CombinedSicActivitiesApiModel.java, src/main/java/uk/gov/companieshouse/siccode/api/search/CombinedSicActivitiesStorageModel.java, src/test/java/uk/gov/companieshouse/siccode/api/search/CombinedSicActivitiesRepositoryTest.java, src/test/java/uk/gov/companieshouse/siccode/api/search/SicCodeTestData.java
Api will now send back a search score for matched sic codes
Update tests after this change
Add test to search on sic code
Add comments in classes to give more context
BI-10828
=> Add search_score to api and api model

src/main/java/uk/gov/companieshouse/siccode/api/search/CombinedSicActivitiesStorageModel.java, src/test/java/uk/gov/companieshouse/siccode/api/search/SicCodeServiceTest.java, src/test/java/uk/gov/companieshouse/siccode/api/search/SicCodeTestData.java
- add new generation_date field to storageModel
- update test date to include new field
=> add new date field

Makefile, pom.xml, src/main/java/uk/gov/companieshouse/siccode/api/search/CombinedSicActivitiesApiModel.java, src/main/java/uk/gov/companieshouse/siccode/api/search/CombinedSicActivitiesStorageModel.java, suppress.xml
- Added security (dependency) check to project
- Also removed some duplication from the maven pom
- Added some Sonar ignore for equals methods where the method is generated via the IDE
[BI-11544](https://companieshouse.atlassian.net/browse/BI-11544)
[BI-11544]: https://companieshouse.atlassian.net/browse/BI-11544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add security checks to sic-code-api

terraform/groups/ecs-service/main.tf
=> fix pipeline error

terraform/groups/ecs-service/data.tf, terraform/groups/ecs-service/locals.tf
=> update terraform to fix error

terraform/groups/ecs-service/locals.tf
=> terraform change to fix error

terraform/groups/ecs-service/data.tf
=> add secrets service

terraform/groups/ecs-service/locals.tf
=> add service secrets var

src/main/java/uk/gov/companieshouse/siccode/api/Logging/InterceptorConfig.java
exclude healthcheck in interceptor config
=> exclude healthcheck in interceptor config

src/main/java/uk/gov/companieshouse/siccode/api/Logging/InterceptorConfig.java, src/test/java/uk/gov/companieshouse/siccode/api/search/HealthCheckControllerTest.java
=> edit healthcheck exclusion and update test

src/main/java/uk/gov/companieshouse/siccode/api/search/SicCodeController.java, src/test/java/uk/gov/companieshouse/siccode/api/search/SicCodeControllerTest.java
Altered search url to match terraform config in `locals.tf` file 
=> make search on /internal/sic-code-search/search

src/main/java/uk/gov/companieshouse/siccode/api/search/SicCodeController.java, src/main/java/uk/gov/companieshouse/siccode/api/search/SicCodeSearchRequestApiModel.java, src/main/java/uk/gov/companieshouse/siccode/api/search/SicCodeService.java, src/test/java/uk/gov/companieshouse/siccode/api/search/HealthCheckControllerTest.java, src/test/java/uk/gov/companieshouse/siccode/api/search/SicCodeControllerTest.java, src/test/java/uk/gov/companieshouse/siccode/api/search/SicCodeServiceTest.java
use x request from eric web
[BI-13661](https://companieshouse.atlassian.net/browse/BI-13661)
[BI-13661]: https://companieshouse.atlassian.net/browse/BI-13661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=>  use x request from eric web

pom.xml
Amended companies house parent version and added sonar properties
=> Amended companies house parent version and added sonar properties

terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
Amended staging and live profiles to not use env files
=> Amended staging and live profiles to not use env files

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars, terraform/groups/ecs-service/variables.tf
=> Amended to correct values

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars, terraform/groups/ecs-service/variables.tf
=> Amend task count config

terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
=> turn on debug to investigate error

src/main/java/uk/gov/companieshouse/siccode/api/search/CombinedSicActivitiesRepository.java
Trying to add repository annotation to fix deployment issues
=> Trying to add repository annotation to fix deployment issues
